
name: Build and deploy

on:
  push:
    branches:
      - main

concurrency:
  group: "pages"
  cancel-in-progress: false

permissions:
  issues: write
  pull-requests: write

jobs:
  Build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Generate Markdown
        run: |
          python3 main.py build

      - name: Build Pages
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |
          yarn run build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: ./src/.vuepress/dist
          alias-domains: groups.sherkey.ml
          vercel-project-name: xmu-groups