
name: Build and deploy

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
  pull_request:
    

concurrency:
  group: "pages"
  cancel-in-progress: false

permissions:
  issues: write

jobs:
  Build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Generate Markdown
        run: |
          python3 main.py build

      - name: Build Pages
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |
          yarn run build

      - name: Deploy to Vercel
        if: github.repository == 'SherkeyXD/XMU-Groups' && github.event_name != 'pull_request'
        run: |
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}