
name: Modify group messages

on:
  workflow_dispatch:
    inputs:
      id:
        description: '群号'
        required: true
      name:
        description: '群名称'
        required: true
      tags:
        description: '群标签'
        required: true
      url:
        description: '加群链接'
        required: true
      create-pr:
        description: '是否自动创建pr'
        default: true
        required: false
        type: boolean

permissions:
  contents: write
  pull-requests: write

jobs:
  Modify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Modify groups.json
        run: |
          python3 main.py modify -id "${{ github.event.inputs.id }}" -name "${{ github.event.inputs.name }}" -tags "${{ github.event.inputs.tags }}" -url "${{ github.event.inputs.url }}"

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with: 
          add: "groups.json"
          message: "group: 修改了群${{ github.event.inputs.id }}的内容"
          new_branch: group-${{ github.event.inputs.id }}

      - name: Create Pull Request
        if: github.repository == 'SherkeyXD/XMU-Groups' && ${{ github.event.inputs.create-pr }}
        run : |
          gh pr create \
          --base main \
          --head $(git branch --show-current) \
          --title "[群信息修改]${{ github.event.inputs.name }}(${{ github.event.inputs.id }})" \
          --body-file "info.md" \
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request from fork to Upstream
        if: github.repository != 'SherkeyXD/XMU-Groups' && ${{ github.event.inputs.create-pr }}
        run : |
          gh pr create \
          --repo SherkeyXD/XMU-Groups \
          --base main \
          --head $(git branch --show-current) \
          --title "[群信息修改]${{ github.event.inputs.name }}(${{ github.event.inputs.id }})" \
          --body-file "info.md" \
        env:
            GH_TOKEN: ${{ secrets.PAT }}  